### ISSUE TITLE
Tool tips for instructors

### ISSUE THREAD

**Issue by dirkcgrunwald** [deraadt/moodle-block_completion_progress#18]
In the student view of the completion bar (which is great, btw), students receive hover-based explanations of what activity each block refers to. It would be great to do this for the instructor view as well -- I've had instructors ask for the ability to better understand what is not being done.

**Comment by deraadt** [comment]
Hi.

I can't replicate that. It seems to work for me.

It may be an interaction with another block that causes this.

Michael
