### ISSUE TITLE
Notice / warning on line 182 when no activities is set in the block

### ISSUE THREAD

**Issue by neeesn** [deraadt/moodle-block_completion_progress#22]
When theres no activities set in the block it casts a php notice and  warning.

Notice: Undefined property: stdClass::$selectactivities in /var/www/moodle/blocks/completion_progress/lib.php on line 182

Warning: in_array() expects parameter 2 to be array, null given in /var/www/moodle/blocks/completion_progress/lib.php on line 182

**Comment by deraadt** [comment]
Thanks for that.
I prefer bugs to be reported on the Moodle Tracker, unless you're pushing a patch.
I've created a fix and will push a new version soon.
