### ISSUE TITLE
Why user selection & action has been removed from overview ?

### ISSUE THREAD

**Issue by T4m** [deraadt/moodle-block_completion_progress#23]
The ability to send a message or write note, to selected users from the course completion overview page was great but has been removed. Is there a reason ? Is there a simple way reactivate the feature ?

The form used to do that is still there in the html (apparently uselessly). The checkboxes and action select dropdown, have been removed.

**Comment by deraadt** [comment]
Hi.
Yes, it would be good to have that messaging functionality again. I removed it when the messaging system changed. I'd be grateful to someone who knows more about the new system to assist.
