### ISSUE TITLE
Privacy API in 3.5 seems not to work

### ISSUE THREAD

**Issue by KerstinSc** [deraadt/moodle-block_completion_progress#29]
Hey,
the privacy API seems not to be working. In the pluginregistry it's still on "This plugin does not implement the Moodle privacy API."

Moodle Version: 3.5 (Build: 20180517)
Plugin Version:  2018060700

Thank you!

**Comment by schach** [comment]
I can confirm this.
The file classes/privacy/provider.php is missing.

**Comment by danmarsden** [comment]
this is also causing unit test failures due to the missing class.

**Comment by deraadt** [comment]
Sorted.
