### ISSUE TITLE
Link to label blank

### ISSUE THREAD

**Issue by amjohnson46** [deraadt/moodle-block_completion_progress#35]
Hi Michael,

For activities in the progress bar, clicking on the cell in the bar takes you to the activity. Really nice! But if the cell is for a label, then the link doesn't work and it sends you to the site front page. Not so nice. I guess there is some property missing on labels that generates this link. Perhaps checking for an empty URL and adding the course main page if empty would solve it?

Thanks,
Aaron

**Comment by deraadt** [comment]
Thanks for reporting.

I've brought in the fix for this.
