### ISSUE TITLE
Overview of Student page doesn't show relevant activity

### ISSUE THREAD

**Issue by sgodbehere01** [deraadt/moodle-block_completion_progress#42]
Hi there,

We appear to have an issue with the latest release of this plug-in on Moodle 3.5.7, On the course page looking at the block hovering over the small blocks shows the relevant activity as expected, as below: 

![Screenshot_2019-07-10 Course Clinical Coaching Veterinary Nursing](https://user-images.githubusercontent.com/31889885/60955900-a9276b00-a2f9-11e9-956c-ebebe330210e.png)

However going to the Overview of Students results in this not happening: 

![Screenshot_2019-07-10 Overview of students](https://user-images.githubusercontent.com/31889885/60955925-b7758700-a2f9-11e9-9741-3d80ac529539.png)

You can't see the pointer but it was certainly hovering over the blocks, clicking on the blocks still seems to work, it just doesn't show the name of the activity. 

As you can see at the bottom there is also an error relating to note_get_state_names. The full error in the logs reads as:

> Default exception handler: Exception - Call to undefined function note_get_state_names() Debug: \nError code: generalexceptionmessage\n* line 361 of /blocks/completion_progress/overview.php: Error thrown\n,

Any ideas what the cause of this issue might be? This appears to be happening on all instances of the block. 

Kind regards,

Sam

**Comment by mgancarzdsi** [comment]
I'm getting the same issue and it's definitely related to the note_get_state_names() call, line 375: https://github.com/deraadt/moodle-block_completion_progress/blob/61fca3c93d7ff0e7799b29b6e1b4757f645e9c5e/overview.php#L375

Temporarily commenting that line out on my testing environment seems to not have any impacts. It looks to be related to the Moodle Notes feature: https://docs.moodle.org/37/en/Notes but I have notes disabled on my site. Even enabling the Notes feature under Advanced features doesn't fix the issue for me.

I think it's just missing the library call near the top., ie:
require_once($CFG->dirroot.'/notes/lib.php');

**Comment by giselebrugger** [comment]
Yes @mgancarzdsi i have the same error after upgrade to version 2.8 in moodle 3.5.1
After I added
require_once($CFG->dirroot.'/notes/lib.php');
its ok now. Thank you.

**Comment by sgodbehere01** [comment]
Hi @mgancarzdsi 

Thanks for that, I can also confirm that adding
`require_once($CFG->dirroot.'/notes/lib.php');` in overview.php
has resolved the issue for us as well. 

Thanks again,

Sam
