### ISSUE TITLE
Multilang Tags are not filtered properly.

### ISSUE THREAD

**Issue by mifantrax** [deraadt/moodle-block_completion_progress#8]
Thank you for the great plugin.

Block Version for Moodle 2.7 onwards - 2016090500
Moodle Version - 3.1.3+ (Build: 20161208)
There is problem with Completion Progress which was not an issue in Progress Bar.
Multi lang Tags (old or the new "{mlang}") are not filtered properly and are visible when hovering over the completion blocks or in the overview mode.
Here is the view in old Progres Bar
![2016-12-12 10_17_54-course_ pt 512 servant leadership - rick justice session 4 - 2016](https://cloud.githubusercontent.com/assets/2910506/21093948/d9690344-c054-11e6-9b67-41414753f105.png)

Here is the view with Completion Progress

![2016-12-12 10_14_00-course_ pt 512 servant leadership - rick justice georgia - 2017](https://cloud.githubusercontent.com/assets/2910506/21093950/d96b0e8c-c054-11e6-95c6-214396f2fd38.png)
![2016-12-12 10_14_14-course_ pt 512 servant leadership - rick justice georgia - 2017](https://cloud.githubusercontent.com/assets/2910506/21093947/d9688482-c054-11e6-82a0-c15fa6eabf50.png)
![2016-12-12 10_20_11-overview of students](https://cloud.githubusercontent.com/assets/2910506/21093949/d96a22e2-c054-11e6-92a4-40118ce3ccf7.png)

Is this fixable ? Should we continue on using the Progress Bar or should we wait for an update on Completion Progress ?

Thank you very much.

**Comment by deraadt** [comment]
Fixed.
